from yacs.config import CfgNode as CN

CFG = CN()

CFG.ELASTOMER = CN()
CFG.ELASTOMER.DENSITY = 1.0E+3
CFG.ELASTOMER.YOUNGS = 1.0E+6
CFG.ELASTOMER.POISSONS = 0.3
CFG.ELASTOMER.LOSS = CN()
CFG.ELASTOMER.LOSS.PDE = 1.0E-10
CFG.ELASTOMER.LOSS.GT = 1.0E+3
CFG.ELASTOMER.LOSS.VEL = 1.0E+3
CFG.ELASTOMER.LOSS.BC = 1.0E-9
CFG.ELASTOMER.LOSS.IC = 0.0
